### ISSUE TITLE
GCC 9 Updates needed

### ISSUE THREAD

**Issue by smuzaffar** [cms-externals/CheckerGccPlugins#1]
@gartung , while building it for gcc 9.0.1 we saw build errors. Looks like there are some fixes related to GCC 9 here https://gitlab.cern.ch/atlas/atlasexternals/commit/8e4cae894c872310bf295b9d19bd0b2b40fdeb49

Can you please update make a PR with the updates needed for GCC 9?

**Comment by smuzaffar** [comment]
@gartung ping?

**Comment by gartung** [comment]
Sorry. Never saw the first message.

**Comment by smuzaffar** [comment]
no problem, gcc 9 IBs were any way stuck due to ThePeg and HerwigPP errors. But now we have newer version of these and every thing else seems to build so it would be nice to get CheckerGccPlugins fixed too. For now I have removed it from cmsdist gcc9  branch to get IB going.

**Comment by gartung** [comment]
I added the extra flag in the same spot.

**Comment by gartung** [comment]
Never have figured out how to use this plugin.

**Comment by smuzaffar** [comment]
what about the other fixes in .cxx files e.g.

https://gitlab.cern.ch/atlas/atlasexternals/commit/8e4cae894c872310bf295b9d19bd0b2b40fdeb49#0a410d378789604c1ab7e0155f711962a45d0b2e
https://gitlab.cern.ch/atlas/atlasexternals/commit/8e4cae894c872310bf295b9d19bd0b2b40fdeb49#f5febb0b9957c1efad329ce5a270e258f64a2d18

these looks related to gcc9
